musicplayer/musicplayer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("player.urls", namespace='player')),
    path('auth/', include('django.contrib.auth.urls'))]
# urlpatterns += staticfiles_urlpatterns()
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

musicplayer/player/urls.py
from django.urls import path, include
from . import views
from .views import SongList, SongDetail
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


app_name = 'player'
urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.upload, name='upload'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(template_name='player/login.html'),
        name='login'
    ),
    path(
        'logout/',
        # Прямо в описании обработчика укажем шаблон,
        # который должен применяться для отображения возвращаемой страницы.
        # Да, во view-классах так можно! Как их не полюбить.
        LogoutView.as_view(template_name='player/logged_out.html'),
        name='logout'
    ),
    path('songs/', SongList.as_view()),
    path('songs/<int:pk>/', SongDetail.as_view()),
    path('auth/', include('djoser.urls')),
    # JWT-эндпоинты, для управления JWT-токенами:
    path('auth/', include('djoser.urls.jwt')),
]

musicplayer/player/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


# Create your models here.
class Song(models.Model):
    title = models.CharField(max_length=255, blank=True)
    artist = models.CharField(max_length=255, blank=True)
    file = models.FileField(upload_to="media")
    DJ = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='mix',
        null=True
    )

musicplayer/player/forms.py
from django import forms

from .models import Song
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # укажем модель, с которой связана создаваемая форма
        model = User
        # укажем, какие поля должны быть видны в форме и в каком порядке
        fields = ('first_name', 'last_name', 'username', 'email')


class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ("title", "artist", "file")

musicplayer/player/views.py
from django.shortcuts import render, redirect
from .forms import SongForm
from .models import Song
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CreationForm
from rest_framework import generics

from .models import Song
from .serializers import SongSerializer

def upload(request):
    if request.method == "POST":
        form = SongForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.DJ = request.user
            post.save()
            return redirect("player:index")
    else:
        form = SongForm()
    return render(request, "player/upload.html", {"form": form})


# this is for showing all songs on the home page
def index(request):
    if request.user.is_authenticated:
        songs = Song.objects.filter(DJ=request.user)
        return render(request, "player/index.html", {"songs": songs})
    else:
        return redirect('player:login')



class SignUp(CreateView):
    form_class = CreationForm
    # После успешной регистрации перенаправляем пользователя на главную.
    success_url = reverse_lazy('player:index')
    template_name = 'player/signup.html'


class SongList(generics.ListCreateAPIView):
    queryset =Song.objects.all()
    serializer_class = SongSerializer


class SongDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Song.objects.all()
    serializer_class = SongSerializer
# Create your views here.

musicplayer/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/player.css' %}">
    {% block title %}
    <title>Home</title>
    {% endblock title %}
</head>
<header>
    <nav>
      <a href="{% url 'player:index' %}"><b>Awesome mix</b></a>
      <a href="{% url 'player:index' %}">Home</a>
      <a href="{% url 'player:upload' %}">Upload</a>
        <a class="auth" href="{% url 'player:logout' %}" >Quit</a>
        <a class="auth" href="{% url 'player:login' %}" >Auth</a>
      <a class="auth" href="{% url 'player:signup' %}" >Registration</a>


    </nav>
  </header>
<body>
      <main>
        {% block content %}{% endblock %}
      </main>
      {% block footer %}

    {% endblock footer %}
</body>
</html>

musicplayer/templates/player/index.html
<style>
  footer {
        position: static;
        left: 0;
        bottom: 0;
        z-index: 6;
        height: 54px;
        width: 100%;
        overflow: hidden;
        border: 0px dotted green;
        background: #f8f7f1;
  }
</style>
{% include "base.html" %}
{% block title %}
      <title>Home</title>
{% endblock title %}
{% block content %}
{% for song in songs %}
    <h2>{{ song.title}}</h2>
    <p>{{song.artist}}</p>
    <audio controls>
        <source src="/static{{ song.file.url }}" type="audio/mpeg">
    </audio>
{% endfor %}
{% endblock %}
<div class="footer-margin"> Футер, который всегда будет внизу</div>
{% block footer %}

      <footer>
        <p>Copyright © 2023 My Music App</p>
      </footer>
    {% endblock footer %}

musicplayer/templates/player/logged_out.html
{% extends 'base.html' %}
{% block content %}
<p align="left" >Logged out!</p>

<a href="{% url 'player:login'%}">Click here to login again.</a>

{% endblock %} 

musicplayer/templates/player/login.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
  {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
  {% else %}
    <p>Please login to see this page.</p>
  {% endif %}
{% endif %}

<form method="post" action="{% url 'player:login' %}">
{% csrf_token %}
<table>

<tr>
  <td>{{ form.username.label_tag }}</td>
  <td>{{ form.username }}</td>
</tr>

<tr>
  <td>{{ form.password.label_tag }}</td>
  <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

musicplayer/templates/player/signup.html
{% extends "base.html" %}
{% block title %}
      <title>Registration</title>
{% endblock title %}
{% block content %}
  <form method="post" action="{% url 'player:signup' %}">
    {% csrf_token %}
      <div class = 'parent'>
    {{ form.as_p }}
          </div>
    <input type="submit" value="Зарегистрироваться">
  </form>
{% endblock %}

musicplayer/templates/player/upload.html
{% extends "base.html" %}
{% block title %}
<title>Upload</title>
{% endblock title %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Upload">
</form>
{% endblock %}
{% block footer %}
      <footer>
        <p>Copyright © 2023 My Music App</p>
      </footer>
    {% endblock footer %}